export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const INVALID_LOGIN = "INVALID_LOGIN";
export const LOGIN_NETWORK_ERROR = "LOGIN_NETWORK_ERROR";
export const LOGOUT = "LOGOUT";
export const  UPDATE_SAVE= "UPDATE_SAVE";
export const COMPLETE_ONBOARDING="COMPLETE_ONBOARDING";
export const START_ONBOARDING = "START_ONBOARDING"


